// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GMail {
    
    
    public partial class GMailConfiguration {
        
        private Gtk.Alignment alignment1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label5;
        
        private Gtk.Label label1;
        
        private Gtk.SpinButton timeout;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView labelTreeView;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Button btnMoveUp;
        
        private Gtk.Button btnMoveDown;
        
        private Gtk.Button btnRemove;
        
        private Gtk.HBox hbox5;
        
        private Gtk.Label label2;
        
        private Gtk.Entry label;
        
        private Gtk.Button btnAdd;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GMail.GMailConfiguration
            Stetic.BinContainer.Attach(this);
            this.Name = "GMail.GMailConfiguration";
            // Container child GMail.GMailConfiguration.Gtk.Container+ContainerChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.BorderWidth = ((uint)(8));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Check _Every");
            this.label5.UseUnderline = true;
            this.hbox3.Add(this.label5);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox3[this.label5]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("mins");
            this.hbox3.Add(this.label1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.label1]));
            w2.PackType = ((Gtk.PackType)(1));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.timeout = new Gtk.SpinButton(1, 600, 1);
            this.timeout.CanFocus = true;
            this.timeout.Name = "timeout";
            this.timeout.Adjustment.PageIncrement = 5;
            this.timeout.ClimbRate = 1;
            this.timeout.Numeric = true;
            this.timeout.Value = 15;
            this.hbox3.Add(this.timeout);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox3[this.timeout]));
            w3.PackType = ((Gtk.PackType)(1));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.vbox1.Add(this.hbox3);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.labelTreeView = new Gtk.TreeView();
            this.labelTreeView.CanFocus = true;
            this.labelTreeView.Name = "labelTreeView";
            this.scrolledwindow1.Add(this.labelTreeView);
            this.hbox1.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.scrolledwindow1]));
            w6.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.btnMoveUp = new Gtk.Button();
            this.btnMoveUp.Sensitive = false;
            this.btnMoveUp.CanFocus = true;
            this.btnMoveUp.Name = "btnMoveUp";
            this.btnMoveUp.UseUnderline = true;
            this.btnMoveUp.Label = Mono.Unix.Catalog.GetString("Move _Up");
            this.vbox2.Add(this.btnMoveUp);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox2[this.btnMoveUp]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.btnMoveDown = new Gtk.Button();
            this.btnMoveDown.Sensitive = false;
            this.btnMoveDown.CanFocus = true;
            this.btnMoveDown.Name = "btnMoveDown";
            this.btnMoveDown.UseUnderline = true;
            this.btnMoveDown.Label = Mono.Unix.Catalog.GetString("Move _Down");
            this.vbox2.Add(this.btnMoveDown);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.btnMoveDown]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.btnRemove = new Gtk.Button();
            this.btnRemove.Sensitive = false;
            this.btnRemove.CanFocus = true;
            this.btnRemove.Name = "btnRemove";
            this.btnRemove.UseUnderline = true;
            this.btnRemove.Label = Mono.Unix.Catalog.GetString("_Remove");
            this.vbox2.Add(this.btnRemove);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.btnRemove]));
            w9.Position = 2;
            w9.Expand = false;
            w9.Fill = false;
            this.hbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Add _Label");
            this.label2.UseUnderline = true;
            this.hbox5.Add(this.label2);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox5[this.label2]));
            w12.Position = 0;
            w12.Expand = false;
            w12.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.label = new Gtk.Entry();
            this.label.CanFocus = true;
            this.label.Name = "label";
            this.label.IsEditable = true;
            this.label.InvisibleChar = '●';
            this.label.Xalign = 1F;
            this.hbox5.Add(this.label);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox5[this.label]));
            w13.Position = 1;
            // Container child hbox5.Gtk.Box+BoxChild
            this.btnAdd = new Gtk.Button();
            this.btnAdd.CanFocus = true;
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.UseUnderline = true;
            this.btnAdd.Label = Mono.Unix.Catalog.GetString("_Add");
            this.hbox5.Add(this.btnAdd);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox5[this.btnAdd]));
            w14.Position = 2;
            w14.Expand = false;
            w14.Fill = false;
            this.vbox1.Add(this.hbox5);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
            w15.Position = 2;
            w15.Expand = false;
            w15.Fill = false;
            this.alignment1.Add(this.vbox1);
            this.Add(this.alignment1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.label5.MnemonicWidget = this.timeout;
            this.Show();
            this.timeout.FocusOutEvent += new Gtk.FocusOutEventHandler(this.OnTimeoutFocusOut);
            this.btnMoveUp.Clicked += new System.EventHandler(this.OnMoveUpClicked);
            this.btnMoveDown.Clicked += new System.EventHandler(this.OnMoveDownClicked);
            this.btnRemove.Clicked += new System.EventHandler(this.OnRemoveClicked);
            this.btnAdd.Clicked += new System.EventHandler(this.OnAddClicked);
        }
    }
}
