// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Docky.Services.GUI {
    
    public partial class UsernameWidget {
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label3;
        
        private Gtk.Entry Username;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Docky.Services.GUI.UsernameWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Docky.Services.GUI.UsernameWidget";
            // Container child Docky.Services.GUI.UsernameWidget.Gtk.Container+ContainerChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.WidthRequest = 70;
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("_Username:");
            this.label3.UseUnderline = true;
            this.hbox3.Add(this.label3);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox3[this.label3]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.Username = new Gtk.Entry();
            this.Username.CanFocus = true;
            this.Username.Name = "Username";
            this.Username.IsEditable = true;
            this.Username.WidthChars = 15;
            this.Username.InvisibleChar = '●';
            this.hbox3.Add(this.Username);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.Username]));
            w2.Position = 1;
            this.Add(this.hbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
