// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Docky.Services.GUI {
    
    public partial class AnonymousWidget {
        
        private Gtk.VBox vbox3;
        
        private Gtk.RadioButton Anon;
        
        private Gtk.RadioButton AsUser;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Docky.Services.GUI.AnonymousWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Docky.Services.GUI.AnonymousWidget";
            // Container child Docky.Services.GUI.AnonymousWidget.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.Anon = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Connect _anonymously"));
            this.Anon.CanFocus = true;
            this.Anon.Name = "Anon";
            this.Anon.DrawIndicator = true;
            this.Anon.UseUnderline = true;
            this.Anon.Group = new GLib.SList(System.IntPtr.Zero);
            this.vbox3.Add(this.Anon);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox3[this.Anon]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.AsUser = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Connect as u_ser:"));
            this.AsUser.CanFocus = true;
            this.AsUser.Name = "AsUser";
            this.AsUser.DrawIndicator = true;
            this.AsUser.UseUnderline = true;
            this.AsUser.Group = this.Anon.Group;
            this.vbox3.Add(this.AsUser);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox3[this.AsUser]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.Anon.Clicked += new System.EventHandler(this.AnonClicked);
            this.AsUser.Clicked += new System.EventHandler(this.UserClicked);
        }
    }
}
