// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Docky.Services.GUI {
    
    public partial class PasswordSaveWidget {
        
        private Gtk.VBox vbox2;
        
        private Gtk.RadioButton Forget;
        
        private Gtk.RadioButton Logout;
        
        private Gtk.RadioButton Forever;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Docky.Services.GUI.PasswordSaveWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Docky.Services.GUI.PasswordSaveWidget";
            // Container child Docky.Services.GUI.PasswordSaveWidget.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.Forget = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Forget password _immediately"));
            this.Forget.CanFocus = true;
            this.Forget.Name = "Forget";
            this.Forget.DrawIndicator = true;
            this.Forget.UseUnderline = true;
            this.Forget.Group = new GLib.SList(System.IntPtr.Zero);
            this.vbox2.Add(this.Forget);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.Forget]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.Logout = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Remember password until you _logout"));
            this.Logout.CanFocus = true;
            this.Logout.Name = "Logout";
            this.Logout.DrawIndicator = true;
            this.Logout.UseUnderline = true;
            this.Logout.Group = this.Forget.Group;
            this.vbox2.Add(this.Logout);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.Logout]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.Forever = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Remember _forever"));
            this.Forever.CanFocus = true;
            this.Forever.Name = "Forever";
            this.Forever.DrawIndicator = true;
            this.Forever.UseUnderline = true;
            this.Forever.Group = this.Forget.Group;
            this.vbox2.Add(this.Forever);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.Forever]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
