// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Docky.Services.GUI {
    
    public partial class PasswordWidget {
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.Entry PasswordEntry;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Docky.Services.GUI.PasswordWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Docky.Services.GUI.PasswordWidget";
            // Container child Docky.Services.GUI.PasswordWidget.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.WidthRequest = 70;
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("_Password:");
            this.label1.UseUnderline = true;
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.PasswordEntry = new Gtk.Entry();
            this.PasswordEntry.CanFocus = true;
            this.PasswordEntry.Name = "PasswordEntry";
            this.PasswordEntry.IsEditable = true;
            this.PasswordEntry.WidthChars = 15;
            this.PasswordEntry.Visibility = false;
            this.PasswordEntry.InvisibleChar = '●';
            this.hbox1.Add(this.PasswordEntry);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.PasswordEntry]));
            w2.Position = 1;
            this.Add(this.hbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
