// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Docky {
    
    public partial class ConfigurationWindow {
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.VBox vbox3;
        
        private Gtk.CheckButton checkbutton1;
        
        private Gtk.CheckButton cpu_saver_checkbox;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Label label2;
        
        private Gtk.ComboBox theme_combo;
        
        private Gtk.ComboBox monitor_combo;
        
        private Gtk.Label GtkLabel2;
        
        private Gtk.VBox vbox5;
        
        private Gtk.Frame dock_placement_frame;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.VBox vbox4;
        
        private Gtk.Alignment dock_pacement_align;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Button add_button;
        
        private Gtk.Button delete_button;
        
        private Gtk.Label GtkLabel6;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.Frame frame3;
        
        private Gtk.Alignment GtkAlignment5;
        
        private Gtk.Notebook configuration_widget_notebook;
        
        private Gtk.Label label1;
        
        private Gtk.Label GtkLabel5;
        
        private Gtk.HBox hbox2;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Button close_button;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Docky.ConfigurationWindow
            this.Name = "Docky.ConfigurationWindow";
            this.Title = Mono.Unix.Catalog.GetString("Docky Configuration");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-preferences", Gtk.IconSize.Menu, 16);
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            // Container child Docky.ConfigurationWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Homogeneous = true;
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.checkbutton1 = new Gtk.CheckButton();
            this.checkbutton1.CanFocus = true;
            this.checkbutton1.Name = "checkbutton1";
            this.checkbutton1.Label = Mono.Unix.Catalog.GetString("Start When Computer Starts");
            this.checkbutton1.DrawIndicator = true;
            this.checkbutton1.UseUnderline = true;
            this.vbox3.Add(this.checkbutton1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox3[this.checkbutton1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.cpu_saver_checkbox = new Gtk.CheckButton();
            this.cpu_saver_checkbox.TooltipMarkup = "Warning! Checking this box may severely hurt the rendering speed of Docky. This option prevents docky from keeping several caches and buffers.";
            this.cpu_saver_checkbox.CanFocus = true;
            this.cpu_saver_checkbox.Name = "cpu_saver_checkbox";
            this.cpu_saver_checkbox.Label = Mono.Unix.Catalog.GetString("Low Memory Mode [Slow Rendering]");
            this.cpu_saver_checkbox.DrawIndicator = true;
            this.cpu_saver_checkbox.UseUnderline = true;
            this.vbox3.Add(this.cpu_saver_checkbox);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox3[this.cpu_saver_checkbox]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Background Appearance:");
            this.hbox4.Add(this.label2);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox4[this.label2]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.theme_combo = Gtk.ComboBox.NewText();
            this.theme_combo.Name = "theme_combo";
            this.hbox4.Add(this.theme_combo);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox4[this.theme_combo]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.monitor_combo = Gtk.ComboBox.NewText();
            this.monitor_combo.Name = "monitor_combo";
            this.hbox4.Add(this.monitor_combo);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox4[this.monitor_combo]));
            w5.PackType = ((Gtk.PackType)(1));
            w5.Position = 2;
            w5.Expand = false;
            w5.Fill = false;
            this.vbox3.Add(this.hbox4);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
            w6.Position = 2;
            w6.Expand = false;
            w6.Fill = false;
            this.GtkAlignment.Add(this.vbox3);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel2 = new Gtk.Label();
            this.GtkLabel2.Name = "GtkLabel2";
            this.GtkLabel2.LabelProp = Mono.Unix.Catalog.GetString("<b>General Options</b>");
            this.GtkLabel2.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel2;
            this.vbox2.Add(this.frame1);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.dock_placement_frame = new Gtk.Frame();
            this.dock_placement_frame.Name = "dock_placement_frame";
            this.dock_placement_frame.ShadowType = ((Gtk.ShadowType)(0));
            // Container child dock_placement_frame.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.dock_pacement_align = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.dock_pacement_align.Name = "dock_pacement_align";
            this.vbox4.Add(this.dock_pacement_align);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox4[this.dock_pacement_align]));
            w10.Position = 0;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            this.hbuttonbox2.LayoutStyle = ((Gtk.ButtonBoxStyle)(1));
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.add_button = new Gtk.Button();
            this.add_button.CanFocus = true;
            this.add_button.Name = "add_button";
            this.add_button.UseStock = true;
            this.add_button.UseUnderline = true;
            this.add_button.Relief = ((Gtk.ReliefStyle)(2));
            this.add_button.Label = "gtk-add";
            this.hbuttonbox2.Add(this.add_button);
            Gtk.ButtonBox.ButtonBoxChild w11 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.add_button]));
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.delete_button = new Gtk.Button();
            this.delete_button.CanFocus = true;
            this.delete_button.Name = "delete_button";
            this.delete_button.UseStock = true;
            this.delete_button.UseUnderline = true;
            this.delete_button.Relief = ((Gtk.ReliefStyle)(2));
            this.delete_button.Label = "gtk-remove";
            this.hbuttonbox2.Add(this.delete_button);
            Gtk.ButtonBox.ButtonBoxChild w12 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.delete_button]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            this.vbox4.Add(this.hbuttonbox2);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbuttonbox2]));
            w13.Position = 1;
            w13.Expand = false;
            w13.Fill = false;
            this.GtkAlignment2.Add(this.vbox4);
            this.dock_placement_frame.Add(this.GtkAlignment2);
            this.GtkLabel6 = new Gtk.Label();
            this.GtkLabel6.Name = "GtkLabel6";
            this.GtkLabel6.LabelProp = Mono.Unix.Catalog.GetString("<b>Dock Placement</b>");
            this.GtkLabel6.UseMarkup = true;
            this.dock_placement_frame.LabelWidget = this.GtkLabel6;
            this.vbox5.Add(this.dock_placement_frame);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox5[this.dock_placement_frame]));
            w16.Position = 0;
            this.vbox2.Add(this.vbox5);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox2[this.vbox5]));
            w17.Position = 1;
            this.hbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
            w18.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.RightPadding = ((uint)(5));
            this.alignment1.BottomPadding = ((uint)(5));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.frame3 = new Gtk.Frame();
            this.frame3.Name = "frame3";
            this.frame3.ShadowType = ((Gtk.ShadowType)(2));
            // Container child frame3.Gtk.Container+ContainerChild
            this.GtkAlignment5 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment5.Name = "GtkAlignment5";
            this.GtkAlignment5.LeftPadding = ((uint)(12));
            this.GtkAlignment5.RightPadding = ((uint)(10));
            this.GtkAlignment5.BottomPadding = ((uint)(10));
            // Container child GtkAlignment5.Gtk.Container+ContainerChild
            this.configuration_widget_notebook = new Gtk.Notebook();
            this.configuration_widget_notebook.CanFocus = true;
            this.configuration_widget_notebook.Name = "configuration_widget_notebook";
            this.configuration_widget_notebook.CurrentPage = 0;
            this.configuration_widget_notebook.ShowBorder = false;
            this.configuration_widget_notebook.ShowTabs = false;
            // Notebook tab
            Gtk.Label w19 = new Gtk.Label();
            w19.Visible = true;
            this.configuration_widget_notebook.Add(w19);
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("page1");
            this.configuration_widget_notebook.SetTabLabel(w19, this.label1);
            this.label1.ShowAll();
            this.GtkAlignment5.Add(this.configuration_widget_notebook);
            this.frame3.Add(this.GtkAlignment5);
            this.GtkLabel5 = new Gtk.Label();
            this.GtkLabel5.Name = "GtkLabel5";
            this.GtkLabel5.LabelProp = Mono.Unix.Catalog.GetString("<b>Dock Configuration</b>");
            this.GtkLabel5.UseMarkup = true;
            this.frame3.LabelWidget = this.GtkLabel5;
            this.alignment1.Add(this.frame3);
            this.hbox1.Add(this.alignment1);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.hbox1[this.alignment1]));
            w23.Position = 1;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w24.Position = 0;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            this.hbox2.Add(this.hbox3);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.hbox2[this.hbox3]));
            w25.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.close_button = new Gtk.Button();
            this.close_button.CanFocus = true;
            this.close_button.Name = "close_button";
            this.close_button.UseStock = true;
            this.close_button.UseUnderline = true;
            this.close_button.BorderWidth = ((uint)(5));
            this.close_button.Label = "gtk-close";
            this.hbox2.Add(this.close_button);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.hbox2[this.close_button]));
            w26.Position = 1;
            w26.Expand = false;
            w26.Fill = false;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w27.Position = 1;
            w27.Expand = false;
            w27.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 728;
            this.DefaultHeight = 418;
            this.Show();
            this.theme_combo.Changed += new System.EventHandler(this.OnThemeComboChanged);
            this.monitor_combo.Changed += new System.EventHandler(this.OnMonitorComboChanged);
            this.add_button.Clicked += new System.EventHandler(this.OnAddButtonClicked);
            this.delete_button.Clicked += new System.EventHandler(this.OnDeleteButtonClicked);
            this.close_button.Clicked += new System.EventHandler(this.OnCloseButtonClicked);
        }
    }
}
