// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WeatherDocklet {
    
    
    public partial class WeatherConfiguration {
        
        private Gtk.Alignment alignment1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label4;
        
        private Gtk.ComboBox source;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Label aboutLabel;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView locationTreeView;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Button btnMoveUp;
        
        private Gtk.Button btnMoveDown;
        
        private Gtk.Button btnRemove;
        
        private Gtk.HBox hbox5;
        
        private Gtk.Label label2;
        
        private Gtk.Entry location;
        
        private Gtk.Button btnSearch;
        
        private Gtk.Button btnAdd;
        
        private Gtk.ScrolledWindow scrolledwindow2;
        
        private Gtk.TreeView searchTreeView;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label5;
        
        private Gtk.Label label1;
        
        private Gtk.SpinButton timeout;
        
        private Gtk.CheckButton metric;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget WeatherDocklet.WeatherConfiguration
            Stetic.BinContainer.Attach(this);
            this.Name = "WeatherDocklet.WeatherConfiguration";
            // Container child WeatherDocklet.WeatherConfiguration.Gtk.Container+ContainerChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.BorderWidth = ((uint)(8));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("_Weather Provider");
            this.label4.UseUnderline = true;
            this.hbox2.Add(this.label4);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox2[this.label4]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.source = Gtk.ComboBox.NewText();
            this.source.Name = "source";
            this.hbox2.Add(this.source);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.source]));
            w2.PackType = ((Gtk.PackType)(1));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.aboutLabel = new Gtk.Label();
            this.aboutLabel.Name = "aboutLabel";
            this.aboutLabel.LabelProp = Mono.Unix.Catalog.GetString("Some information about the weather source.");
            this.aboutLabel.Wrap = true;
            this.hbox4.Add(this.aboutLabel);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox4[this.aboutLabel]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            this.vbox1.Add(this.hbox4);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.locationTreeView = new Gtk.TreeView();
            this.locationTreeView.CanFocus = true;
            this.locationTreeView.Name = "locationTreeView";
            this.scrolledwindow1.Add(this.locationTreeView);
            this.hbox1.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.scrolledwindow1]));
            w7.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.btnMoveUp = new Gtk.Button();
            this.btnMoveUp.Sensitive = false;
            this.btnMoveUp.CanFocus = true;
            this.btnMoveUp.Name = "btnMoveUp";
            this.btnMoveUp.UseUnderline = true;
            this.btnMoveUp.Label = Mono.Unix.Catalog.GetString("Move _Up");
            this.vbox2.Add(this.btnMoveUp);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.btnMoveUp]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.btnMoveDown = new Gtk.Button();
            this.btnMoveDown.Sensitive = false;
            this.btnMoveDown.CanFocus = true;
            this.btnMoveDown.Name = "btnMoveDown";
            this.btnMoveDown.UseUnderline = true;
            this.btnMoveDown.Label = Mono.Unix.Catalog.GetString("Move _Down");
            this.vbox2.Add(this.btnMoveDown);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.btnMoveDown]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.btnRemove = new Gtk.Button();
            this.btnRemove.Sensitive = false;
            this.btnRemove.CanFocus = true;
            this.btnRemove.Name = "btnRemove";
            this.btnRemove.UseUnderline = true;
            this.btnRemove.Label = Mono.Unix.Catalog.GetString("_Remove");
            this.vbox2.Add(this.btnRemove);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.btnRemove]));
            w10.Position = 2;
            w10.Expand = false;
            w10.Fill = false;
            this.hbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w12.Position = 2;
            w12.Expand = false;
            w12.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Add _Location");
            this.label2.UseUnderline = true;
            this.hbox5.Add(this.label2);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox5[this.label2]));
            w13.Position = 0;
            w13.Expand = false;
            w13.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.location = new Gtk.Entry();
            this.location.CanFocus = true;
            this.location.Name = "location";
            this.location.IsEditable = true;
            this.location.InvisibleChar = '●';
            this.location.Xalign = 1F;
            this.hbox5.Add(this.location);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox5[this.location]));
            w14.Position = 1;
            // Container child hbox5.Gtk.Box+BoxChild
            this.btnSearch = new Gtk.Button();
            this.btnSearch.CanFocus = true;
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.UseUnderline = true;
            this.btnSearch.Label = Mono.Unix.Catalog.GetString("_Search");
            this.hbox5.Add(this.btnSearch);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox5[this.btnSearch]));
            w15.Position = 2;
            w15.Expand = false;
            w15.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.btnAdd = new Gtk.Button();
            this.btnAdd.CanFocus = true;
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.UseUnderline = true;
            this.btnAdd.Label = Mono.Unix.Catalog.GetString("_Add");
            this.hbox5.Add(this.btnAdd);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox5[this.btnAdd]));
            w16.Position = 3;
            w16.Expand = false;
            w16.Fill = false;
            this.vbox1.Add(this.hbox5);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
            w17.Position = 3;
            w17.Expand = false;
            w17.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.scrolledwindow2 = new Gtk.ScrolledWindow();
            this.scrolledwindow2.CanFocus = true;
            this.scrolledwindow2.Name = "scrolledwindow2";
            this.scrolledwindow2.HscrollbarPolicy = ((Gtk.PolicyType)(2));
            this.scrolledwindow2.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow2.Gtk.Container+ContainerChild
            this.searchTreeView = new Gtk.TreeView();
            this.searchTreeView.CanFocus = true;
            this.searchTreeView.Name = "searchTreeView";
            this.searchTreeView.HeadersVisible = false;
            this.searchTreeView.SearchColumn = 0;
            this.scrolledwindow2.Add(this.searchTreeView);
            this.vbox1.Add(this.scrolledwindow2);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow2]));
            w19.Position = 4;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Automatically Update _Every");
            this.label5.UseUnderline = true;
            this.hbox3.Add(this.label5);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox3[this.label5]));
            w20.Position = 0;
            w20.Expand = false;
            w20.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("mins");
            this.hbox3.Add(this.label1);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox3[this.label1]));
            w21.PackType = ((Gtk.PackType)(1));
            w21.Position = 1;
            w21.Expand = false;
            w21.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.timeout = new Gtk.SpinButton(5, 720, 5);
            this.timeout.CanFocus = true;
            this.timeout.Name = "timeout";
            this.timeout.Adjustment.PageIncrement = 10;
            this.timeout.ClimbRate = 5;
            this.timeout.Numeric = true;
            this.timeout.Value = 30;
            this.hbox3.Add(this.timeout);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox3[this.timeout]));
            w22.PackType = ((Gtk.PackType)(1));
            w22.Position = 2;
            w22.Expand = false;
            w22.Fill = false;
            this.vbox1.Add(this.hbox3);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
            w23.Position = 5;
            w23.Expand = false;
            w23.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.metric = new Gtk.CheckButton();
            this.metric.CanFocus = true;
            this.metric.Name = "metric";
            this.metric.Label = Mono.Unix.Catalog.GetString("Use _Metric Units");
            this.metric.DrawIndicator = true;
            this.metric.UseUnderline = true;
            this.vbox1.Add(this.metric);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox1[this.metric]));
            w24.Position = 6;
            w24.Expand = false;
            w24.Fill = false;
            this.alignment1.Add(this.vbox1);
            this.Add(this.alignment1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.label4.MnemonicWidget = this.source;
            this.label2.MnemonicWidget = this.location;
            this.label5.MnemonicWidget = this.timeout;
            this.Show();
            this.source.Changed += new System.EventHandler(this.OnSourceChanged);
            this.btnMoveUp.Clicked += new System.EventHandler(this.OnMoveUpClicked);
            this.btnMoveDown.Clicked += new System.EventHandler(this.OnMoveDownClicked);
            this.btnRemove.Clicked += new System.EventHandler(this.OnRemoveClicked);
            this.btnSearch.Clicked += new System.EventHandler(this.OnSearchClicked);
            this.btnAdd.Clicked += new System.EventHandler(this.OnAddClicked);
            this.timeout.FocusOutEvent += new Gtk.FocusOutEventHandler(this.OnTimeoutFocusOut);
            this.metric.FocusOutEvent += new Gtk.FocusOutEventHandler(this.OnMetricFocusOut);
        }
    }
}
